mount:
  workspace: '../../Documents/workspace'
  m2: '../../.m2'
vbguest:
  auto_update: false
  no_remote: true
vb:
  memory: 3078
  cpus: 2
rsync:
  excludes:
    - .git/
    - 'classes/config/application.yml'
  latency: 2.5