mount:
  rsync: ./rsync
  workspace: '../../Documents/workspace'
  m2: '../../.m2'
  vagrant:
    - ./apps
    - ./oracle
vbguest:
  auto_update: false
  no_remote: true
vb:
  memory: 3078
  cpus: 2
rsync:
  excludes:
    - .git/
    - 'classes/config/application.yml'
  latency: 1.5
hostsupdater:
  aliases:
    - 'local.co.jp'