version: '2'
services:
  oracle-datastore:
    image: busybox
    volumes:
        - ./_data:/opt/oracle/oradata
    container_name: oracle-datastore
  oracle:
    tty: true
    image: oracle/database:12.2.0.1-ee
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    privileged: true
    user: oracle
    volumes_from:
      - oracle-datastore
    volumes:
      - ./sqlplus/scripts:/home/oracle/sqlplus
  sqlplus:
    tty: true
    build: ./sqlplus
    image: sqlplus
    container_name: sqlplus
    volumes:
      - ./sqlplus/scripts:/scripts
    links:
      - oracle:oracle.db.jp
    command: /bin/sh
  sub-oracle-datastore:
    image: busybox
    volumes:
        - ./_sub_data:/opt/oracle/oradata
    container_name: sub-oracle-datastore
  sub-oracle:
    tty: true
    image: oracle/database:12.2.0.1-ee
    container_name: sub-oracle
    ports:
      - "1921:1521"
      - "5900:5500"
    privileged: true
    user: oracle
    volumes_from:
      - sub-oracle-datastore
    volumes:
      - ./sqlplus/scripts:/home/oracle/sqlplus
    links:
      - oracle:oracle.db.jp
networks:
  default:
    external:
      name: common_link