version: '2'
services:
  t6j6:
    tty: true
    build:
      context: ./t6j6
      args:
        CONTEXT_PATH: t6j6
    image: t6j6
    container_name: t6j6
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - /workspace/Tomcat6Java6Ant01/src/main/webapp:/usr/local/tomcat/webapps/t6j6
      - ./t6j6:/run-scripts
    command: /run-scripts/executeContainer.sh
    environment:
      VIRTUAL_HOST: local.co.jp
      # VIRTUAL_PORT: 8080
      VIRTUAL_PORT: 8443
  boot10:
    tty: true
    image: spring-boot:latest
    container_name: boot10
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - /workspace/spring-boot-10:/app
      - ./boot10:/run-scripts
      - /m2:/root/.m2
    command: /run-scripts/executeContainer.sh
  smtp:
    image: schickling/mailcatcher
    container_name: smtp
    ports:
      - "1080:1080"
      - "1025:1025"
networks:
  default:
    external:
      name: common_link